<?= $this->doctype(); ?>

<html lang="fr">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('ZF2 '. $this->translate('My administration'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this
                ->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(
            [
                'rel' => 'shortcut icon',
                'type' => 'image/vnd.microsoft.icon',
                'href' => $this->basePath() . '/img/favicon.ico'
            ]
            )
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('bower_components/bootstrap/dist/css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('bower_components/bootstrap/dist/js/bootstrap.min.js'))
            ->prependFile($this->basePath('bower_components/jquery/dist/jquery.min.js'))
        ; ?>
    </head>

    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?= $this->url('home'); ?>">
                        <img
                            src="<?= $this->basePath('img/zf2-logo.png'); ?>"
                            alt="Zend Framework 2" />&nbsp;
                        <?= $this->translate('Skeleton Application'); ?>
                    </a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active">
                            <a href="<?= $this->url('home'); ?>">
                                <?= $this->translate('Home'); ?>
                            </a>
                        </li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>

        <div class="container">
            <?= $this->content; ?>
            <hr>
            <footer>
                <p>&copy; <?= date('Y') ?> by Christina Vandendyck <?= $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->

        <?= $this->inlineScript() ?>
    </body>
</html>
