<?php
/**
 * Created by PhpStorm.
 * User: Chris
 * Date: 13/05/2016
 * Time: 15:56
 */

?>

<section class="content-header">
    <h1>
        Administration
        <small>Index of the administration</small>
    </h1>
    <ol class="breadcrumb">
        <li>
            <a href="#">
                <i class="fa fa-dashboard"></i>
                Level
            </a>
        </li>
        <li class="active">Here</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    You are on the index page of the administration.
    <hr>
</section>



