<?php
/**
 * Created by PhpStorm.
 * User: Chris
 * Date: 02/06/2016
 * Time: 16:57
 */

$loginForm->prepare();
?>

<div class="container">

    <div class="col-md-6 col-md-offset-3">

        <div class="box box-info">

            <div class="box-header with-border">
                <h3 class="box-title">Login </h3>
            </div>
        </div>

        <?= $this->form()->openTag($loginForm) ?>

            <div class="box-body">
                <?= $this->formElement($loginForm->get('csrf_connect')); ?>

                <div class="form-group">
                    <?= $this->formLabel($loginForm->get('username')); ?>

                    <div class="col-sms-10">
                        <?= $this->formElement($loginForm->get('username')) ?>
                        <?= $this->formElementErrors($loginForm->get('username')); ?>
                    </div>
                </div>

                <div class="form-group">
                    <?= $this->formLabel($loginForm->get('password')); ?>

                    <div class="col-sms-10">
                        <?= $this->formElement($loginForm->get('password')) ?>
                        <?= $this->formElementErrors($loginForm->get('password')); ?>
                    </div>
                </div>

                <div class="form-group">
                    <?= $this->formElement($loginForm->get('rememberMe')) ?>
                    Remember ME
                </div>
            </div>

            <div class="box-footer">
                <button class="btn btn-primary" type="submit">
                    Sign in
                </button>
            </div>
        <?= $this->form()->closeTag() ?>

    </div>

</div>
