<?php
/**
 * Created by PhpStorm.
 * User: Chris
 * Date: 25/05/2016
 * Time: 13:10
 */

$registerForm->prepare();

?>


<div class="container">

    <div class="col-md-6 col-md-offset-3">

        <div class="box box-info">

            <div class="box-header with-border">
                <h3 class="box-title">Register an account</h3>
            </div>

            <?= $this->form()->openTag($registerForm); ?>

                <div class="box-body">

                    <div class="form-group">
                        <?= $this->formLabel($registerForm->get('username')); ?>

                        <?= $this->formElement($registerForm->get('username')); ?>
                        <?= $this->formElementErrors($registerForm->get('username')); ?>
                    </div>

                    <div class="form-group">
                        <?= $this->formLabel($registerForm->get('email')); ?>

                        <?= $this->formElement($registerForm->get('email')); ?>
                        <?= $this->formElementErrors($registerForm->get('email')); ?>
                    </div>

                    <div class="form-group">
                        <?= $this->formLabel($registerForm->get('firstName')); ?>

                        <?= $this->formElement($registerForm->get('firstName')); ?>
                        <?= $this->formElementErrors($registerForm->get('firstName')); ?>
                    </div>

                    <div class="form-group">
                        <?= $this->formLabel($registerForm->get('lastName')); ?>

                        <?= $this->formElement($registerForm->get('lastName')); ?>
                        <?= $this->formElementErrors($registerForm->get('lastName')); ?>
                    </div>

                    <div class="form-group">
                        <?= $this->formLabel($registerForm->get('password')); ?>

                        <?= $this->formElement($registerForm->get('password')); ?>
                        <?= $this->formElementErrors($registerForm->get('password')); ?>
                    </div>

                    <div class="form-group">
                        <?= $this->formLabel($registerForm->get('passwordVerify')); ?>

                        <?= $this->formElement($registerForm->get('passwordVerify')); ?>
                        <?= $this->formElementErrors($registerForm->get('passwordVerify')); ?>
                    </div>

                    <div class="form-group">
                        <?= $this->formLabel($registerForm->get('role')); ?>

                        <?= $this->formElement($registerForm->get('role')); ?>
                        <?= $this->formElementErrors($registerForm->get('role')); ?>
                    </div>

                </div>

                <div class="box-footer">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>

            <?= $this->form()->closeTag(); ?>
        </div>

    </div>
</div>

