<?php
/**
 * Created by PhpStorm.
 * User: Chris
 * Date: 16/06/2016
 * Time: 16:15
 */


?>

<!-- Logo -->
<a href="index2.html" class="logo">
    <!-- mini logo for sidebar mini 50x50 pixels -->
    <span class="logo-mini"><b>A</b>LT</span>
    <!-- logo for regular state and mobile devices -->
    <span class="logo-lg"><b>Admin</b>LTE</span>
</a>

<?= $this->partial('partials/header-nav.phtml'); ?>
